// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5c437qCGyd8_U8EX1igja4hr1AFsHR6g',
    appId: '1:466263979814:web:461d66312113cd1b3d73e7',
    messagingSenderId: '466263979814',
    projectId: 'auth-demo-b5a68',
    authDomain: 'auth-demo-b5a68.firebaseapp.com',
    storageBucket: 'auth-demo-b5a68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDej88-LsaCxcDJww1ro9oGIjJv_nxQMi4',
    appId: '1:466263979814:android:14468491f9f76d203d73e7',
    messagingSenderId: '466263979814',
    projectId: 'auth-demo-b5a68',
    storageBucket: 'auth-demo-b5a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAlDTlSma0Z6fIarOEvGPdZHRRqPVms_k',
    appId: '1:466263979814:ios:c235a0bf4dc154013d73e7',
    messagingSenderId: '466263979814',
    projectId: 'auth-demo-b5a68',
    storageBucket: 'auth-demo-b5a68.appspot.com',
    iosBundleId: 'com.example.authDemo',
  );
}
